### ISSUE TITLE
Requesting Add Edit Chat Feature 

### ISSUE THREAD

**Issue by Shiva6699** [Shiva607/WhatsApp#2]
Dear Shiva607

I would be great if the app is capable adding edit chat feature as well, Kindly add this feature.

**Comment by Shiva607** [comment]
Dear Shiva6699, Thanks for suggesting this feature. We will add it and let you know.

**Comment by Shiva607** [comment]
Dear Shiva6699, Thanks for your valuable suggestion. This feature is going to make our product great
